config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :tasks do
    post "toggle_status", on: :member
    post "sort", on: :collection
  end
  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_many :tasks, dependent: :destroy
  belongs_to :user
  default_scope{ order('created_at DESC') }
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :project
  acts_as_list scope: :project
  after_create :set_position

  def toggle_complete
    if status == "incomplete"
      update status: "complete"
    else
      update status: "incomplete"
      self.move_to_bottom
    end
  end

  def set_position
    self.move_to_top
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :defaults

  has_many :projects, dependent: :destroy

  def defaults
    project = Project.create!(name: "My First List", user_id: id)
    Task.create!(name: "Click&drag dots to sort tasks", project_id: project.id)
    Task.create!(name: "Click on list name to edit it", project_id: project.id)
    Task.create!(name: "Click on task to edit it", project_id: project.id)
    Task.create!(name: "Click “Create new list” to add a list", project_id: project.id)
    Task.create!(name: "Click checkmark to complete task", project_id: project.id)
    Task.create!(name: "Put mouse cursor over task", project_id: project.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :new_task, only: [:index, :create, :new]
  before_action :authenticate_user!
  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
    respond_to :js
  end

  def create
    @project = Project.new(project_params)
    if @project.save 
      respond_to :js 
    else
      render nothing: true
    end
  end

  def edit
    @project = Project.find(params[:id])
    respond_to :js 
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      respond_to :js 
    else
      render nothing: true
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      respond_to :js
    end
  end

  private

    def project_params
      params.require(:project).permit(:name, :user_id)
    end

    def new_task
      @task = Task.new
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  def create
    @task = Task.new(task_params)
    if @task.save
      respond_to :js
    else
      render nothing: true
    end
  end

  def edit
    @task = Task.find(params[:id])
    respond_to :js
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      respond_to :js
    else
      render nothing: true
    end
  end

  def toggle_status
    @task = Task.find(params[:id])
    if @task.toggle_complete
      respond_to :js
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      respond_to :js
    end
  end

  def sort
    params[:task].each_with_index do |id, index|
      Task.where(id: id).update_all(position: index+1)
    end
    render nothing: true
  end

  private

    def task_params
      params.require(:task).permit(:name, :project_id, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_status? status
    status == "incomplete"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<div class="create-project-form">
<%= form_for(project, remote: 'true') do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <%= f.text_field :name%>
  </div>
  <%= f.submit class: "notvis"  %>
<% end %>
</div>

app/views/projects/_project.html.erb
<div class="project-item" data-id="<%= project.id unless project.new_record? %>">
  <div class="project-container">
    <%= link_to "", project, method: :delete, remote: true, class: "project-delete"%>
    <%= render 'form', project: project %>
    <%= render('tasks/form', project: project) unless project.new_record? %>
    <ul class="tasks-list" data-update-url="<%= sort_tasks_url %>">
      <%= render project.tasks.where(status: "incomplete").order('position ASC') %>
    </ul>
    <ul class="tasks-list-complete">
      <%= render project.tasks.where(status: "complete").order("updated_at DESC") %>
    </ul>
  </div>
</div>

app/views/projects/_project_header.html.erb
<div class="project-header">

  <%= link_to project.name, edit_project_path(project), remote: :true, class: "project-title" %>

<!-- 
  <%= link_to "Remove", project, method: :delete, remote: :true %>
   -->
</div>

app/views/projects/create.js.erb
$(".project-item:first").remove()
$(".projects-list").prepend('<%= j render("project", project: @project)%>')
$(".project-item:first .create-task-name input").focus()

$('.projects-list .project-item:first ul').sortable({
    placeholder: "ui-state-highlight",
    axis: "y",
    update: function( event, ui ) {
      $.post($(this).data('update-url'), $(this).sortable('serialize'))
    }
  });

app/views/projects/destroy.js.erb
$(".project-item[data-id='" + "<%= @project.id%>" + "']").remove()

app/views/projects/edit.js.erb
$(".project-item[data-id='" + "<%= @project.id%>" + "'] .project-header").remove()
$(".project-item[data-id='" + "<%= @project.id%>" + "']").prepend("<%= j render('form', project: @project) %>")
$(".project-item[data-id='" + "<%= @project.id%>" + "'] .create-project-form input").focus()

app/views/projects/index.html.erb
<div class="container">
<% if notice %><p class="notice"><%= notice %></p><% end %>
<% if alert %><p class="alert"><%= alert %></p><% end %>
<div class="projects-list">
  <%= render @projects %>
</div>
<div class="user">
  <span class="email"><%= current_user.email %></span>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "logout"%>
</div>
<%= link_to new_project_path, remote: :true , id: "add-project" do%>
  <div class="create-list">
    <span>Create new list</span>
  </div>
<% end %>
</div>

app/views/projects/new.js.erb
$(".projects-list").prepend("<%= j render('project', project: @project) %>")
$(".projects-list .project-item:first .create-project-form .field input").focus()

app/views/projects/update.js.erb
/*$(".project-item[data-id='" + "<%= @project.id%>" + "'] .create-project-form").remove()
$(".project-item[data-id='" + "<%= @project.id%>" + "'] .project-title").html('<%= @project.name%>')
$(".project-item[data-id='" + "<%= @project.id%>" + "']").prepend('<%= j render("project_header", project: @project)%>')*/
$(".project-item[data-id='" + "<%= @project.id%>" + "'] .create-project-form .field input").blur()

app/views/tasks/_form.html.erb
<div class="create-task">
  <%= form_for(@task, remote: true) do |f| %>
    <%= f.hidden_field :project_id, value: project.id %>
    <div class="create-task-name">
      <%= f.text_field :name, placeholder: "What should be done?" %>   
    </div>
    <%= f.submit class: "notvis" %>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<li class="task task_<%= task.id %>" id='<%= "task_#{task.id}" %>'>
  <div class="task-container">
  <%= link_to "", toggle_status_task_path(task), remote: true, method: :post, class: "checkmark" %>
  <div class="drag"></div>
  <%= link_to "",task, method: :delete, remote: true, class: "task-delete"%>
  <%= form_for(task, remote: true) do |f| %>
    <div class="create-task-name">
      <%= f.text_field :name %>   
    </div>
  <% end %>
  </div>
</li>

app/views/tasks/create.js.erb
$(".project-item[data-id='"+"<%= @task.project.id %>" + "'] ul.tasks-list").prepend("<%= j render('task', task:@task) %>")

var el = $(".project-item[data-id='"+"<%= @task.project.id %>" + "'] ul li:first")
el.css("opacity", "0");
el.css("height", "0");
el.css("opacity");
el.css("opacity", "1");
el.css("height", "5.3vw");
$(".project-item[data-id='"+"<%= @task.project.id %>" + "'] .create-task form #task_name").val("")
$(".project-item[data-id='"+"<%= @task.project.id %>" + "'] .create-task form #task_name").focus()

app/views/tasks/destroy.js.erb
$("li.task_" + "<%= @task.id %>").remove()

app/views/tasks/edit.js.erb
$("li.task_" + "<%= @task.id %>").replaceWith("<%= j render('form', project: @task.project) %>")

app/views/tasks/toggle_status.js.erb
$("li.task_" + "<%= @task.id %>").remove()
if ("<%= @task.status %>" == "complete") {
  $(".project-item[data-id='" + "<%= @task.project.id %>" + "'] .tasks-list-complete").prepend("<%= j render 'task', task: @task%>")
} else {
  $(".project-item[data-id='" + "<%= @task.project.id %>" + "'] .tasks-list").append("<%= j render 'task', task: @task%>")
};

app/views/tasks/update.js.erb
/*$("form#edit_task_" + "<%= @task.id%>").replaceWith("<%= j render('task', task:@task) %>")*/
$("form#edit_task_" + "<%= @task.id%> .create-task-name #task_name").blur()